package Panel;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class Fondo extends javax.swing.JPanel {
    
    private Icon backgroundpicture;

    public Icon getBackgroundpicture() {
        return backgroundpicture;
    }

    public void setBackgroundpicture(Icon backgroundpicture) {
        this.backgroundpicture = backgroundpicture;
    }
    
    /**
     * Creates new form Fondo
     */
    
    public Fondo() {
        initComponents();
        setOpaque(true);
    }
    
    //paints a background picture if selected
    @Override
    public void paint(Graphics g) {
        if (backgroundpicture != null) {
            Image img = ((ImageIcon)backgroundpicture).getImage();
            g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        else{
            super.paint(g);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
